### ISSUE TITLE
Закрытие кредита

### ISSUE THREAD

**Issue by varlogen** [apmath-web/credit-go#15]
Для создания метода нужно сделать:

- имплементация метода удаления кредита из репозитория

- обработка запроса credit/id method=delete

- логика обработки ошибок согласно спецификации

- настроить роутинг для метода

**Comment by malinink** [comment]
Это вы в 4 будете удаление делать?
Если так, то предлагаю разделить на 2 отдельные задачи, первая `ddd` вторая `api`

**Comment by malinink** [comment]
И да, в задаче мы не ставим чекбоксы
