### ISSUE TITLE
Не соответствие спецификации метода получения платежей

### ISSUE THREAD

**Issue by levkovalenko** [apmath-web/credit-go#27]
https://docs.google.com/document/d/1jJT-Vsn8LIrJiOjc5IwOjfP7wIftqV6yCc_uAKWMC_E/edit#heading=h.f1ollw1gpqwa
не проверяется условие  (type==next && state==paid)

**Comment by malinink** [comment]
Это не корректная спецификация.
Я подправил описание, в таком случае должно быть 200OK и пустой массив

**Comment by levkovalenko** [comment]
окей,  Баг устарел.
