### ISSUE TITLE
Реализовать метод платежа по кредиту

### ISSUE THREAD

**Issue by levkovalenko** [apmath-web/credit-go#29]
- Создать Value Object для платежа
- Сделать regular платежи
- Решить проблемы с датой
- Реализовать early платежи
- Решить проблему с наложением платежей
- Сделать перерасчет кредита

- Добавить вывод платежей
- Добавить тестирвоание

**Comment by malinink** [comment]
Была мысль что, возможно, добаввлять месяцы к дате начале не очень хорошо, достаточно ведь только брать из неё число. Мне показалось что это ещё проще и ничего подсчитывать не надо.
Да и хранить тоже, просто извлекаем число из даты `agreementAt` и проверяем что она есть в месяца платежа, если нет - берем последний день из месяца.
Что скажете? @levozavr @BarracudaPff
