### ISSUE TITLE
Создание ViewModel для метода удаления кредита

### ISSUE THREAD

**Issue by TimurSirkin** [apmath-web/credit-go#7]
### Описать методы:

- [ ] **Получить ID из URL**

- [ ] **Валидация**
  - \[ ] Проверить, что ID целое положительное число
  - \[ ] Проверить, что кредит с таким ID существует

- [ ] **Удаление кредита**
  - \[ ] Проверить, что кредит с таким ID закрыт
  - \[ ] Удалить кредит

**Comment by malinink** [comment]
@TimurSirkin для удаления кредите viewModel не нужен, предлагаю пересмотреть список дел, которые необходимы.
